### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by diamond-darrell**
### Submitting a change

This library is auto-generated using `kaltura/clients-generator` php engine. Feel free to clone, build and play with this library but in order to submit PR you should work against the [kaltura/clients-generator](https://github.com/kaltura/clients-generator) repo. 

If your fix is not complex you can open an issue or even a PR and we will consider adding it on our own to the generator.

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kalturageneratedapiclientstypescript/5)

### CODE REVIEW

**Comment by esakal** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/tests/tests-config.tpl.ts, line 2 at r1](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5#-KyHeanjA8_WASzBiRIn:-KyHeankqaCbRCHTyOUC:bcrzrcb) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/e69a437f908afad853ef6e6f0db65f0edce5239c/src/tests/tests-config.tpl.ts#L2)):*
> ```XML
> export const TestsConfig = {
>   endpoint: "@endpoint@",
> ```

Did you adjust the code to use the same configuration as in python? [see their config.ini](https://github.com/kaltura/KalturaGeneratedAPIClientsPython/blob/master/KalturaClient/tests/config.ini)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5)*

**Comment by diamond-darrell** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/tests/tests-config.tpl.ts, line 2 at r1](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5#-KyHeanjA8_WASzBiRIn:-KyHrm8QXdw2SXUSn-Hp:b-actpwi) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/e69a437f908afad853ef6e6f0db65f0edce5239c/src/tests/tests-config.tpl.ts#L2)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

Did you adjust the code to use the same configuration as in python? [see their config.ini](https://github.com/kaltura/KalturaGeneratedAPIClientsPython/blob/master/KalturaClient/tests/config.ini)
</blockquote></details>

Yes, I used this config to generate ks, we have already discussed it, python lib has a function that can generate ks from this config and TS lib doesn't so I just generate ks in `testme console` and put generated ks into config.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5)*

**Comment by esakal** [comment]
Review status: 0 of 16 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5#-KyIJtLXvs5SW6d0ZLe-:-KyIJtLXvs5SW6d0ZLe0:b-iki5d) (no related file):*
+@diamond-darrell please review changes between revision r1 and r2  by clicking here



---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5#-KyILd4enuDA5v4gZAgE:-KyILd4enuDA5v4gZAgF:b-vd7t31) (no related file):*
Use the following `tests-config.ts` file:

```
export const TestsConfig = {
    partnerId: "1931861",
    userName: "testUser",
    adminSecret: "83c3d4449a3abbe92ca5966f5f010eb4",
    endpointUrl: "https://www.kaltura.com/api_v3",
    clientTag: "typescript-tests"
};
```

---

*[package.json, line 27 at r2](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5#-KyIKILu7a7G_cLwvJug:-KyIKILu7a7G_cLwvJuh:b-24isk0) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/ea1343827477e0b14fddc3fccb65db36b775efd6/package.json#L27)):*
> ```JSON
>     "watch": "gulp watch",
>     "release": "standard-version",
>     "test": "jest service-distribution.spec"
> ```

I only refactored distribution so I limit the jest execution to that service. Remove it once you refactor the reset of the services.

---

*[src/kaltura-logger.ts, line 2 at r2](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5#-KyIKRQ2pNUBL1ohEJKk:-KyIKRQ3N9Z0-NnIFNGV:b-e1lwu5) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/ea1343827477e0b14fddc3fccb65db36b775efd6/src/kaltura-logger.ts#L2)):*
> ```XML
> 
> export enum LogLevels
> ```

I added basic log implementation so I will be able to suspend warnings from kaltura-clients. If you want to understand why just comment the log level assignment in the `BeforeAll` function of the distribution.

---

*[src/kaltura-object-base.ts, line 247 at r2](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5#-KyIKgDrlTP3tpFbjM1P:-KyIKgDrlTP3tpFbjM1Q:bku2s6n) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/ea1343827477e0b14fddc3fccb65db36b775efd6/src/kaltura-object-base.ts#L247)):*
> ```XML
>         if (usedFallbackType && result)
>         {
>                 logger.warn(`[kaltura-typescript-client]: Could not find object type '${objectType}', Falling back to '${fallbackObjectType}' object type. (Did you remember to set your accepted object types in the request “acceptedTypes” attribute?)`);
> ```

using the new logger so tests will be able to suspend those warnings.

---

*[src/tests/service-distribution.spec.ts, line 1 at r1](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5#-KyIKkDns26BAYSm25F8:-KyIKkDns26BAYSm25F9:b-u8ryd1) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/e69a437f908afad853ef6e6f0db65f0edce5239c/src/tests/service-distribution.spec.ts#L1)):*
> ```XML
> import { TestsConfig } from "./tests-config";
> ```

can use factory function to create the client, no need to duplicate that logic.

---

*[src/tests/service-distribution.spec.ts, line 11 at r2](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5#-KyIKt_AGCBMBhN53NWx:-KyIKt_AGCBMBhN53NWy:bviz77q) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/ea1343827477e0b14fddc3fccb65db36b775efd6/src/tests/service-distribution.spec.ts#L11)):*
> ```XML
> import { KalturaEntryDistributionListResponse } from "../types/KalturaEntryDistributionListResponse";
> import { KalturaEntryDistribution } from "../types/KalturaEntryDistribution";
> import { getClient } from "./utils";
> ```

continuing of comment - "can use factory function to create the client, no need to duplicate that logic".

---

*[src/tests/service-distribution.spec.ts, line 17 at r2](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5#-KyIKzMNQi4Gfci1NFW0:-KyIKzMNQi4Gfci1NFW1:b-8xp7k2) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/ea1343827477e0b14fddc3fccb65db36b775efd6/src/tests/service-distribution.spec.ts#L17)):*
> ```XML
>   let kalturaClient: KalturaBrowserHttpClient = null;
> 
>     beforeAll(async () => {
> ```

async is essential otherwise it won't work. Also can use `beforeAll` since I don't think it contribute anything doing it during `beforeEach`

---

*[src/tests/service-distribution.spec.ts, line 38 at r2](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5#-KyILEASlJoos1zlhrRO:-KyILEASlJoos1zlhrRP:bhbcqjr) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/ea1343827477e0b14fddc3fccb65db36b775efd6/src/tests/service-distribution.spec.ts#L38)):*
> ```XML
>         },
>         (error) => {
>           fail(error);
> ```

when you refactor your code, replace the static message with the actual error, this is quite important to debug failures from the log file

---

*[src/tests/tests-config.tpl.ts, line 2 at r1](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5#-KyHeanjA8_WASzBiRIn:-KyILNPAfg7oSbBqtrzo:bfqalpz) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/e69a437f908afad853ef6e6f0db65f0edce5239c/src/tests/tests-config.tpl.ts#L2)):*
<details><summary><i>Previously, diamond-darrell wrote…</i></summary><blockquote>

Yes, I used this config to generate ks, we have already discussed it, python lib has a function that can generate ks from this config and TS lib doesn't so I just generate ks in `testme console` and put generated ks into config.
</blockquote></details>

I provided a valid configuration file as a separated comment 

---

*[src/tests/utils.ts, line 21 at r2](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5#-KyILjas2j4ITBJVVpR5:-KyILjas2j4ITBJVVpR6:b-bjk3n) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/ea1343827477e0b14fddc3fccb65db36b775efd6/src/tests/utils.ts#L21)):*
> ```XML
> 
> 
>     return client.request(new SessionStartAction({
> ```

I'm using a relevant service to generate a ks based on admin secret. I saw what they did in python and it is possible to just copy the logic from there but I think a cleaner approach will be to use the api itself. 

I took this logic from [here](https://github.com/kaltura/KalturaGeneratedAPIClientsNodeJS/blob/master/test/media.js#L23)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5)*

**Comment by esakal** [comment]
Reviewed 10 of 14 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5#-KyILd4enuDA5v4gZAgE:-KyKEA7VOrHj-eHakhLk:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

Use the following `tests-config.ts` file:

```
export const TestsConfig = {
    partnerId: "1931861",
    userName: "testUser",
    adminSecret: "83c3d4449a3abbe92ca5966f5f010eb4",
    endpointUrl: "https://www.kaltura.com/api_v3",
    clientTag: "typescript-tests"
};
```
</blockquote></details>

OK

---

*[a discussion](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5#-KyIJtLXvs5SW6d0ZLe-:-KyKFvXla8EQNEGlOFbV:b32w0x) (no related file):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

+@diamond-darrell please review changes between revision r1 and r2  by clicking here





</blockquote></details>

OK

---

*[package.json, line 27 at r2](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5#-KyIKILu7a7G_cLwvJug:-KyKFzKJAQ8uuWOoVqtW:b32w0x) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/ea1343827477e0b14fddc3fccb65db36b775efd6/package.json#L27)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I only refactored distribution so I limit the jest execution to that service. Remove it once you refactor the reset of the services.
</blockquote></details>

OK

---

*[src/kaltura-logger.ts, line 2 at r2](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5#-KyIKRQ2pNUBL1ohEJKk:-KyKG-4j60nGPSUqYWAd:b32w0x) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/ea1343827477e0b14fddc3fccb65db36b775efd6/src/kaltura-logger.ts#L2)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I added basic log implementation so I will be able to suspend warnings from kaltura-clients. If you want to understand why just comment the log level assignment in the `BeforeAll` function of the distribution.
</blockquote></details>

OK

---

*[src/kaltura-object-base.ts, line 247 at r2](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5#-KyIKgDrlTP3tpFbjM1P:-KyKG0Fz8p-32468UGvn:b32w0x) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/ea1343827477e0b14fddc3fccb65db36b775efd6/src/kaltura-object-base.ts#L247)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

using the new logger so tests will be able to suspend those warnings.
</blockquote></details>

OK

---

*[src/tests/service-distribution.spec.ts, line 1 at r1](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5#-KyIKkDns26BAYSm25F8:-KyKG0wvSyQtdCByRVhy:b32w0x) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/e69a437f908afad853ef6e6f0db65f0edce5239c/src/tests/service-distribution.spec.ts#L1)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

can use factory function to create the client, no need to duplicate that logic.
</blockquote></details>

OK

---

*[src/tests/service-distribution.spec.ts, line 11 at r2](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5#-KyIKt_AGCBMBhN53NWx:-KyKG6LCsj3m-Rs2jVJy:b32w0x) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/ea1343827477e0b14fddc3fccb65db36b775efd6/src/tests/service-distribution.spec.ts#L11)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

continuing of comment - "can use factory function to create the client, no need to duplicate that logic".
</blockquote></details>

OK

---

*[src/tests/service-distribution.spec.ts, line 17 at r2](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5#-KyIKzMNQi4Gfci1NFW0:-KyKGAvkfqsVGsRiYzos:b32w0x) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/ea1343827477e0b14fddc3fccb65db36b775efd6/src/tests/service-distribution.spec.ts#L17)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

async is essential otherwise it won't work. Also can use `beforeAll` since I don't think it contribute anything doing it during `beforeEach`
</blockquote></details>

OK

---

*[src/tests/service-distribution.spec.ts, line 38 at r2](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5#-KyILEASlJoos1zlhrRO:-KyKGD7pEM0FWJoWFI1J:b32w0x) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/ea1343827477e0b14fddc3fccb65db36b775efd6/src/tests/service-distribution.spec.ts#L38)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

when you refactor your code, replace the static message with the actual error, this is quite important to debug failures from the log file
</blockquote></details>

OK

---

*[src/tests/tests-config.tpl.ts, line 2 at r1](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5#-KyHeanjA8_WASzBiRIn:-KyKGEbyvVVUkTOzojRy:b32w0x) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/e69a437f908afad853ef6e6f0db65f0edce5239c/src/tests/tests-config.tpl.ts#L2)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I provided a valid configuration file as a separated comment 
</blockquote></details>

OK

---

*[src/tests/utils.ts, line 21 at r2](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5#-KyILjas2j4ITBJVVpR5:-KyKGFOz0FpjThrzaL1Z:b-5dqpub) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/ea1343827477e0b14fddc3fccb65db36b775efd6/src/tests/utils.ts#L21)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

I'm using a relevant service to generate a ks based on admin secret. I saw what they did in python and it is possible to just copy the logic from there but I think a cleaner approach will be to use the api itself. 

I took this logic from [here](https://github.com/kaltura/KalturaGeneratedAPIClientsNodeJS/blob/master/test/media.js#L23)
</blockquote></details>

Yeah, when I was writing reply to you I understood that if I can create the KS using `testme` console (which is just request builder) why I can't do same using kaltura-client, sorry I should have guessed it before

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5)*

**Comment by esakal** [comment]
Reviewed 7 of 8 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5)*

**Comment by esakal** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5#-:-KyQfFZyr0mmdWTmLAXB:bnfp4nl)*

**Comment by esakal** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5)*

**Comment by esakal** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/5)*

**Pull request merged**
