### PR TITLE
Chunk and resume upload

### PR DESCRIPTION
**Pull request by diamond-darrell**
### Submitting a change

This library is auto-generated using `kaltura/clients-generator` php engine. Feel free to clone, build and play with this library but in order to submit PR you should work against the [kaltura/clients-generator](https://github.com/kaltura/clients-generator) repo. 

If your fix is not complex you can open an issue or even a PR and we will consider adding it on our own to the generator.

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kalturageneratedapiclientstypescript/3)

### CODE REVIEW

**Comment by diamond-darrell** [comment]
+@esakal I merged master to this brunch, but later I'd found that master branch has missing files that and build is failed, so I revert merge commit for this branch, just FYI 

---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/3#-:-Kw9oAP5_cuQ2R7N48k3:b-tgymzu)*

**Comment by esakal** [comment]
OK, Sure, I'm ignoring any changes under `types` folder since I assume those are issues of the merge

---

Reviewed 1 of 3 files at r2, 22 of 22 files at r3.
Review status: 20 of 23 files reviewed at latest revision, 9 unresolved discussions.

---

*[src/kaltura-upload-request.ts, line 12 at r3](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/3#-KwTgP4ZIr3K4ioBF8yK:-KwTgP4ZIr3K4ioBF8yL:b3a316v) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/590061aede842d550f901fae07e6ecf26f069182/src/kaltura-upload-request.ts#L12)):*
> ```XML
> export class KalturaUploadRequest<T> extends KalturaRequest<T> {
>   private _progressCallback: ProgressCallback;
> ```

you are missing a property for the added argument `uploadedFileSize`. the constructor should copy the value from the argument to the request  so it will be available to the clients.

---

*[src/kaltura-upload-request.ts, line 26 at r3](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/3#-KwTaK8snGmVXxCgazvk:-KwTaK8snGmVXxCgazvl:b3kre) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/590061aede842d550f901fae07e6ecf26f069182/src/kaltura-upload-request.ts#L26)):*
> ```XML
>   }
> 
>   public getFormDataPropertyName(): string {
> ```

?

---

*[src/kaltura-upload-request.ts, line 31 at r3](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/3#-KwVfVMjIrUJENuBGb5z:-KwVfVMjIrUJENuBGb6-:b3kre) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/590061aede842d550f901fae07e6ecf26f069182/src/kaltura-upload-request.ts#L31)):*
> ```XML
>   }
> 
>   public getFileData(): File {
> ```

?

---

*[src/kaltura-upload-request.ts, line 37 at r3](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/3#-KwTgk5ST0uobDAVRe2E:-KwTgk5ST0uobDAVRe2F:b-p9gwf6) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/590061aede842d550f901fae07e6ecf26f069182/src/kaltura-upload-request.ts#L37)):*
> ```XML
>   }
> 
>   public getUploadedFileSize(): number {
> ```

`uploadedFileSize` should be a property of the class and be assigned in the constructor by the data provided in the args

---

*[src/kaltura-clients/kaltura-http-client-base.ts, line 38 at r3](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/3#-KwTfQtx31wALEzmLbYP:-KwTfQtydew6F7PitPJo:bethrb0) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/590061aede842d550f901fae07e6ecf26f069182/src/kaltura-clients/kaltura-http-client-base.ts#L38)):*
> ```XML
>   protected _transmitFileUploadRequest(request): CancelableAction {
>     return new CancelableAction((resolve, reject) => {
>       const uploadedFileSize = request.getUploadedFileSize ? request.getUploadedFileSize() : 0;
> ```

you can assume that the `request` is of type `KalturaUploadRequest` as seen [here](https://github.com/kaltura/KalturaGeneratedAPIClientsTypescript/blob/master/src/kaltura-clients/kaltura-client-base.ts#L86)

---

*[src/kaltura-clients/kaltura-http-client-base.ts, line 38 at r3](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/3#-KwTiD-lRrMBfdH5F_rI:-KwTiD-lRrMBfdH5F_rJ:b-xj34lz) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/590061aede842d550f901fae07e6ecf26f069182/src/kaltura-clients/kaltura-http-client-base.ts#L38)):*
> ```XML
>   protected _transmitFileUploadRequest(request): CancelableAction {
>     return new CancelableAction((resolve, reject) => {
>       const uploadedFileSize = request.getUploadedFileSize ? request.getUploadedFileSize() : 0;
> ```

we need to check if the browser support chunk upload. according to [fine-uploader](https://docs.fineuploader.com/features/chunking.html) it is not supported for ie9 for example

---

*[src/kaltura-clients/kaltura-http-client-base.ts, line 38 at r3](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/3#-KwTjmsNa_678edOsQgO:-KwTjmsNa_678edOsQgP:beryyep) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/590061aede842d550f901fae07e6ecf26f069182/src/kaltura-clients/kaltura-http-client-base.ts#L38)):*
> ```XML
>   protected _transmitFileUploadRequest(request): CancelableAction {
>     return new CancelableAction((resolve, reject) => {
>       const uploadedFileSize = request.getUploadedFileSize ? request.getUploadedFileSize() : 0;
> ```

validate size provided by user

---

*[src/kaltura-clients/kaltura-http-client-base.ts, line 78 at r3](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/3#-KwTji1L7HCv1dkWR0QY:-KwTji1L7HCv1dkWR0QZ:b3kre) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/590061aede842d550f901fae07e6ecf26f069182/src/kaltura-clients/kaltura-http-client-base.ts#L78)):*
> ```XML
> 
>       const data = request.getFormData();
>       const file = request.getFileData();
> ```

?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/3#-:-KwVbZJ0RWfaU_rubNph:bkfutu6)*

**Comment by esakal** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/3)*

**Comment by esakal** [comment]
added to the generator in the following PR kaltura/clients-generator#207

**Pull request closed without merging**
