### PR TITLE
Fix upload file in IE11 and edge and Safari

### PR DESCRIPTION
**Pull request by diamond-darrell**
### Submitting a change

This library is auto-generated using `kaltura/clients-generator` php engine. Feel free to clone, build and play with this library but in order to submit PR you should work against the [kaltura/clients-generator](https://github.com/kaltura/clients-generator) repo. 

If your fix is not complex you can open an issue or even a PR and we will consider adding it on our own to the generator.

---
This change is [Reviewable](https://reviewable.io/reviews/kaltura/kalturageneratedapiclientstypescript/6)

### CODE REVIEW

**Comment by esakal** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/kaltura-upload-request.ts, line 65 at r1](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/6#-KylrIZARmzwYZCwB_IK:-KylrIZBCYcpFNMv0PPU:b-c8j6az) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/6b1d4f6477c78940a0b4ce56cef906c459a01925/src/kaltura-upload-request.ts#L65)):*
> ```XML
>     }
> 
>     public getUpdatedFileData(fileChunk: Blob, fileName: string): FormData {
> ```

After reviewing your code and taking into consideration future support for node.js, I think we must detach the logic of form data from the request it self. `FormData` is part of browser specific objects and thus should be part of the client and not of the request. The only thing that is relevant to the request is the property name and the file payload.

I think you should move this new function to the `kaltura-http-client-base` together with the following function to the client-http-base:
```
  public getFormData(): FormData {
        let result = null;
        const filePropertyName = this.getFilePropertyName();

        if (filePropertyName) {
            const file = this[filePropertyName];

            if (file) {
                result = new FormData();
                result.append("fileName", file.name);
                result.append(filePropertyName, file);
            }
        }

        return result;
    }
```
Those two functions are almost identical so you can merge them.

In the request file (this file), consider merging two functions that are used together (just to be sure it is clear this function should remain in the request):
```

    public getFilePropertyName(): string {
      // remove this function
    }

    public getFileData(): File {
        // remove this function  
    }
    
    public _getFileInfo(): { file: File, propertyName: string } {
        const metadataProperties = this._getMetadata().properties;
        const filePropertyName = Object.keys(metadataProperties).find(propertyName => metadataProperties[propertyName].type === "f");

        return filePropertyName ? {propertyName: filePropertyName, file: this[filePropertyName]} : null;
    }
```

Skype me if it is not clear or you think otherwise

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/6)*

**Comment by diamond-darrell** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/kaltura-upload-request.ts, line 65 at r1](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/6#-KylrIZARmzwYZCwB_IK:-KyoaYbSqyQYNsuZ2etz:b32w0x) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/6b1d4f6477c78940a0b4ce56cef906c459a01925/src/kaltura-upload-request.ts#L65)):*
<details><summary><i>Previously, esakal (Eran Sakal) wrote…</i></summary><blockquote>

After reviewing your code and taking into consideration future support for node.js, I think we must detach the logic of form data from the request it self. `FormData` is part of browser specific objects and thus should be part of the client and not of the request. The only thing that is relevant to the request is the property name and the file payload.

I think you should move this new function to the `kaltura-http-client-base` together with the following function to the client-http-base:
```
  public getFormData(): FormData {
        let result = null;
        const filePropertyName = this.getFilePropertyName();

        if (filePropertyName) {
            const file = this[filePropertyName];

            if (file) {
                result = new FormData();
                result.append("fileName", file.name);
                result.append(filePropertyName, file);
            }
        }

        return result;
    }
```
Those two functions are almost identical so you can merge them.

In the request file (this file), consider merging two functions that are used together (just to be sure it is clear this function should remain in the request):
```

    public getFilePropertyName(): string {
      // remove this function
    }

    public getFileData(): File {
        // remove this function  
    }
    
    public _getFileInfo(): { file: File, propertyName: string } {
        const metadataProperties = this._getMetadata().properties;
        const filePropertyName = Object.keys(metadataProperties).find(propertyName => metadataProperties[propertyName].type === "f");

        return filePropertyName ? {propertyName: filePropertyName, file: this[filePropertyName]} : null;
    }
```

Skype me if it is not clear or you think otherwise
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/6)*

**Comment by diamond-darrell** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/kaltura-clients/kaltura-http-client-base.ts, line 114 at r2](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/6#-Kyopm_pZzgexBDOCcf7:-Kyopm_pZzgexBDOCcf8:brxyuwn) ([raw file](https://github.com/kaltura/kalturageneratedapiclientstypescript/blob/7d4511d2dcb781a42868e8ae07dcf5fd66b84732/src/kaltura-clients/kaltura-http-client-base.ts#L114)):*
> ```XML
>             this._assignDefaultParameters(parameters);
> 
>             const { propertyName, file } = request.getFileInfo();
> ```

+@esakal I don't handle false scenario from `getFileInfo`, what should happens if there's no file or propertyName?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/6)*

**Comment by esakal** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/kaltura/kalturageneratedapiclientstypescript/6)*

**Pull request merged**
